### ISSUE TITLE
 checking if enough voting power (NaN >= 50) ?

### ISSUE THREAD

**Issue by fadyro** [Steem-FOSSbot/steem-fossbot-voter#142] opened 2018-04-13 12:41 UTC
My bot is not upvoting:

 **checking if enough voting power (NaN >= 50) :**

2018-04-13T12:38:46.790430+00:00 app[web.1]:  - - 0 < 2000, WILL NOT vote on post [i-will-declare-this-openly-f475d17067214]
2018-04-13T12:38:46.790515+00:00 app[web.1]:  - - recalculating score threshold with window:[2000]
2018-04-13T12:38:46.790576+00:00 app[web.1]:  - - - new avg / score threshold: 2000
2018-04-13T12:38:46.790684+00:00 app[web.1]:  - - - - new threshold info: {"min":10,"average":2000,"variance":0,"percentInc":0,"total":2000}
2018-04-13T12:38:46.790733+00:00 app[web.1]:  - - 0 < 2000, WILL NOT vote on post [xdac-the-potential-platform-designed-as-a-self-sustainable-decentralized-ecosystem]
2018-04-13T12:38:46.790808+00:00 app[web.1]:  - - recalculating score threshold with window:[2000,2000]
2018-04-13T12:38:46.790892+00:00 app[web.1]:  - - - new avg / score threshold: 2000
2018-04-13T12:38:46.790969+00:00 app[web.1]:  - - - - new threshold info: {"min":10,"average":2000,"variance":0,"percentInc":0,"total":2000}
2018-04-13T12:38:46.791108+00:00 app[web.1]:  - - - checking if enough voting power (NaN >= 50) ?
2018-04-13T12:38:46.791162+00:00 app[web.1]:  - - - - NOT voting on man-street-photography-by-dolov, VP is NaN
2018-04-13T12:38:46.791228+00:00 app[web.1]:  - saving avg_window_info
2018-04-13T12:38:46.793251+00:00 app[web.1]: save posts metadata to db...
2018-04-13T12:38:46.793339+00:00 app[web.1]:  - - NOT saving postsmetadata, this is a test run
2018-04-13T12:38:46.793445+00:00 app[web.1]: runBot finished successfully!
2018-04-13T12:38:46.794534+00:00 app[web.1]: persistObj save to db avg_window_info
2018-04-13T12:38:56.795473+00:00 app[web.1]: lib.runBot returned valid results

**Comment by thrize** [comment] 2018-04-14 09:51
I can't reproduce this but I could see that it could happen if getting the information from the account fails, perhaps due to an API failure.

I'm going to wrap this is some error checking and fail well and with a message if we do get an API failure that prevents updating the account's voting power.

We can then check with you after the next release.

**Comment by fadyro** [comment] 2018-04-15 08:36
okay thanks man, please just let me know when ur done to test my side!

**Comment by thrize** [comment] 2018-04-15 20:26
Ready to test now

**Comment by fadyro** [comment] 2018-04-15 20:40
okay let me check, thanks

**Comment by fadyro** [comment] 2018-04-15 20:53
heyy again, please note it is still not doing well,

hence i have enter valid posting key and username:

2018-04-15T20:51:36.248099+00:00 app[web.1]: runBot started...

2018-04-15T20:51:36.249956+00:00 app[web.1]: checking we have enough
voting power...

2018-04-15T20:51:36.250362+00:00 app[web.1]: { message: 'Zero voting
power or error getting voting power: vp = (undefined' }

2018-04-15T20:51:46.258729+00:00 app[web.1]: lib.runBot returned valid results


note that i have voting power,

Thank You

**Comment by thrize** [comment] 2018-04-15 21:01
The voting power gets set as `owner.voting_power` in the start up sequence going to `getUserAccount`. The only reason it would not be set is if your account cannot be found or set.

It's working for me, so I'm thinking that you might not have entered your account name in the environment variables. Go to your Heroku app settings, reveal the config vars and check if you have set the variable `STEEM_USER` with you correct account name.

If it turns out it is correct then I'm going to need to see the full start up logs for a bot run, right from the start. Please redact any personal information but otherwise leave as much there as you can.

**Comment by fadyro** [comment] 2018-04-15 21:51
the username should start with '@' ?

**Comment by fadyro** [comment] 2018-04-15 21:52
i checked it, it is still the same :(

**Comment by fadyro** [comment] 2018-04-15 21:55
look

app[web.1]: { message: 'Zero voting power or error getting voting
power: vp = (*undefined*' }

**Comment by thrize** [comment] 2018-04-15 21:55
No `@` symbol.

**Comment by thrize** [comment] 2018-04-15 21:56
Send me a full log as requested.

**Comment by fadyro** [comment] 2018-04-19 08:45
2018-04-19T08:44:50.199086+00:00 app[web.1]: runBot started...
2018-04-19T08:44:50.200715+00:00 app[web.1]: checking we have enough voting power...
2018-04-19T08:44:50.204088+00:00 app[web.1]: { message: 'Zero voting power or error getting voting power: vp = (undefined' }
2018-04-19T08:45:00.207150+00:00 app[web.1]: lib.runBot returned valid results

**Comment by fadyro** [comment] 2018-04-19 09:06
please note that this occurs when i click on TEST ALGORITHM,
well when i click RUN BOT i can see owner voting power and it continues normally.

Thanks

**Comment by thrize** [comment] 2018-05-04 08:31
@fadyro I need the full log to proceed

**Comment by thrize** [comment] 2018-05-27 16:35
@fadyro I will close this ticket if I don't hear anything soon

**Comment by fadyro** [comment] 2018-05-27 16:53
Yeah please close, i told i guess? It is fine i guess. Thanks

**Comment by ghost** [comment] 2018-06-03 15:46
Okay, thanks

**Closed by ghost** 2018-06-03 15:46 UTC
Labels: needs investigation, server
