### ISSUE TITLE
No votes since 10 hours

### ISSUE THREAD

**Issue by prosmacs** [Steem-FOSSbot/steem-fossbot-voter#153] opened 2018-05-27 14:29 UTC
Hi,

All my bots stopped voting for 10 hours with the following Error Message:

"Unhandled rejection (<{"message":"Error reading posts from s...>, no stack trace)"

Could this be a problem with the steemit api again?

Greetz

**Comment by thrize** [comment] 2018-05-27 16:33
Yes pretty much, the RPC nodes have been returning a lot of errors. There are two relevant things here:

1. I am adding a feature to select which RPC node you want to use in case this happens and you want to try a different one, feature tracked in ticket #151 
2. I am going to improve some logging around errors so it's clearer what the cause is, see #152 for more info on that

Nothing more in particular to add for this ticket, so I'm going to close it but thanks for enquiring.

**Closed** 2018-05-27 16:34 UTC
Labels: nothing-to-do-here, usage
