### ISSUE TITLE
Fix and documentation for single metric algorithms

### ISSUE THREAD

**Issue by taoteh1221** [Steem-FOSSbot/steem-fossbot-voter#24] opened 2017-02-01 17:33 UTC
So I had an issue where using the "author_is_followed, weight = 1000" algorithm was skipping quite a few of my followed authors posts in my feed. Adjusting MIN_SCORE_THRESHOLD to be lower than the default value seemed to clear this issue up. I will have to play with it more to tune it in better, but figured I'd mention this since it is not included yet in the documentation for "author_is_followed, weight = 1000". 

Mentioning carefully tweaking MIN_SCORE_THRESHOLD slowly until feed posts are voted on as desired in the docs might come in handy for some folks using "author_is_followed, weight = 1000". Great bot, thanks a ton for it. Done initial testing, that's all I found so far. Will definitely be firing up my clean machine for a donation very soon. :)

**Comment by thrize** [comment] 2017-02-01 18:59
Thanks @taoteh1221 for that.

It sounds mysterious to my why changing MIN_SCORE_THRESHOLD would solve that, sounds like a bug. I found that the same thing happened to me but it was because the votes in the last 24 hours were over the limit set, i.e. MAX_VOTES_IN_24_HOURS

Just to make sure the cause of it is a bug, would you be able to share a screen grab of the statistic for the bot run? (obviously be careful to only capture that part of the screen!)

**Comment by taoteh1221** [comment] 2017-02-01 20:11
@thrize MAX_VOTES_IN_24_HOURS was set to 1000 / MIN_POST_AGE_TO_CONSIDER set to 1, and I still had issues getting all my followed authors auto-voted. When I set MIN_SCORE_THRESHOLD to 0, it fixed the issue and it is very reliable, only missing one post here and there on rare occasion. I'm not sure which statistic to send you, I'm on the hobby plan with the heroku scheduler auto-running every 10 minutes (works great).

**Comment by thrize** [comment] 2017-02-01 20:14
Okay great, I'll try to replicate that and get to the bottom of the behaviour, thanks.

Glad it's working out for you :D

**Comment by taoteh1221** [comment] 2017-02-01 20:19
@thrize Your welcome, thanks for the cool free bot. :)

**Comment by thrize** [comment] 2017-05-14 17:33
Changed title to reflect issue discovery

**Comment by thrize** [comment] 2017-05-14 20:11
In the [algorithms doc](https://github.com/Steem-FOSSbot/steem-fossbot-voter/blob/master/docs/algorithm.md) the following text was added to explain the situation of what I call _single metric algorithms_, which have to be treated differently due to averaging, especially for where the single metric is boolean, i.e. on or off.

> #### Summary of threshold calculation

> [...]

> Finally, most of this assumes that you have a somewhat complex algorithm, i.e. that a few metrics are used which make the score result complex. However if only one metric is used, the system becomes simple and some of these assumptions do not hold. Please read the next subsection if you use a simple algorithm.

> #### Exceptions

> ##### Single metric algorithms

> There is also a special case for algorithms containing **only one metric**. In this case, only the average will be used **at 90%**, i.e. only _step 1_ from the above, until ```MAX_VOTES_IN_24_HOURS``` at which time the threshold becomes prohibitively high, stopping voting.

> Another detail is that the threshold is used at 90% for this case. This is combat the situation where all scores above ```MIN_SCORE_THRESHOLD``` are the same, and the average will approach and eventually equal this same score value, eventually disabling voting permanently for this algorithm.

> So we have two he threshold _does not_ slowly rise with the percentage of votes left for this 24 period; we found that when only one metric is used this effectively disables voting most of the time (thanks to (at)renzoarg and (at)taoteh for helping with this).
  
> Bear this in mind when designing algorithms with just one metric.

The reason why this was working for you before @taoteh1221 when you set the ```MIN_SCORE_THRESHOLD``` low was because it allowed for "rejected" posts to be included in the averaging calculation, which meant the average would be lower than the "accepted" value, since score values below ```MIN_SCORE_THRESHOLD``` are not factored into the average, to keep it fairly high.

The solution here should work well for you without needing to reduce ```MIN_SCORE_THRESHOLD``` to zero, though it has little use in your use case.

**Comment by thrize** [comment] 2017-05-14 20:12
Fixed in v0.2.8, need to review this quite well to make sure it works

**Comment by thrize** [comment] 2017-05-21 19:11
Confirmed fixed in v0.2.8

**Closed** 2017-05-21 19:11 UTC
Labels: needs investigation, SERIOUS, server, suggestion
